### ISSUE TITLE
Build Hamburger Menu for Mobile (Navbar Responsiveness)

### ISSUE THREAD

**Issue by angeljgomezc** [Developer-DAO/DAO-job-board#10]

**Comment by miralsuthar** [comment]
I can work on this issue

**Comment by angeljgomezc** [comment]
> I can work on this issue

Awesome! You're assigned :)!

**Comment by miralsuthar** [comment]
hey, can you tell when will be the chakra-UI will be implemented in the main branch so I can use the chakra-UI component for the responsiveness?

**Comment by angeljgomezc** [comment]
> hey, can you tell when will be the chakra-UI will be implemented in the main branch so I can use the chakra-UI component for the responsiveness?
> 

Should be up in a few hours, so later today :)
