### ISSUE TITLE
Post isn't working? 

### ISSUE THREAD

**Issue by mayurjobanputra** [Developer-DAO/DAO-job-board#119]
**Describe the bug**
Seems like I can't post a job
![image](https://user-images.githubusercontent.com/6332663/143954059-0b30bab4-3076-490b-a64f-4c471fd11bce.png)

If I click post, nothing happens

**Comment by angeljgomezc** [comment]
The project is still in the works (it's a prototype). We hope to have it ready ASAP! 

Thank you for the interest anyway!
