### ISSUE TITLE
Build out the design system components into the app

### ISSUE THREAD

**Issue by carlomigueldy** [Developer-DAO/DAO-job-board#122]
### Overview

The design team has been working towards building the designs and jazza.eth have laid out the foundations for the design system. Personally I think it would be great that we can prioritize building out the design system components when those were completed. That will allow us to mostly reuse everything and not having to reinvent or rebuild components ourselves.

While having design system components, it would be very awesome to have [storybook](https://storybook.js.org/) integrated so we can preview the design system components that were built. It's my first time to be encountering with storybook so it will be some sort of exploring the unknowns myself, however if you wanna setup storybook please feel free to do so.

Here's the issue for setting up storybook #123 

### Next Steps

When the design components are complete and ready to be built out. A set of cards in the kanban board would be very useful to delegate the tasks and allow for everyone that wans to contribute can contribute easily by building out those small or big components.

**Comment by carlomigueldy** [comment]
I wanna know more of your thoughts on this about storybook

cc @with-heart @Dhaiwat10 @angeljgomezc

**Comment by Dhaiwat10** [comment]
If you're building a collection of re-usable components I think Storybook is a good idea. This would also be a good introduction and learning exercise for folks who are new to Storybook.

**Comment by angeljgomezc** [comment]
Breaking down components in smaller batches so I'll close this issue
