### ISSUE TITLE
Storybook setup

### ISSUE THREAD

**Issue by carlomigueldy** [Developer-DAO/DAO-job-board#123]
### Overview

As mentioned on this #122 we might have to setup storybook. 

Here are the links that I think are useful:
- https://storybook.js.org/
- https://www.npmjs.com/package/@storybook/react
- https://storybook.js.org/addons/@snek-at/storybook-addon-chakra-ui

If it's going to have its own app directory then please have it inside `packages` and not directly in the root directly. We're aiming to move most of the projects in this monorepo snuck into `packages`. And please do so create the relevant scripts for storybook into the root `package.json`

**Comment by christiananese** [comment]
@carlomigueldy I could set this up if no one else is working on this.

**Comment by carlomigueldy** [comment]
Yeah fo sho mate, no one else is working on this @christiananese

**Comment by carlomigueldy** [comment]
Assigning this to you my friend @christiananese
