### ISSUE TITLE
Add more details to database design

### ISSUE THREAD

**Issue by carlomigueldy** [Developer-DAO/DAO-job-board#124]
### Overview

The [database design](https://github.com/Developer-DAO/DAO-job-board/tree/main/database) that I have came up with from weeks ago needs to have more details to be explained to help understand why the decision to come up with such relationship mapping. At the time of writing this the database attributes are out-of-date since we've finally published the [RFC document](https://forum.developerdao.com/t/rfc-user-stories-for-dao-job-board/507) on Discourse and you can tell by the user stories there would be different attributes or database relationships. I will have to write out more details on the database design since I came up with it. And having more details can open up more ideas/suggestions to improve the current database design.

**Comment by sushiAlii** [comment]
hey Carlo, add me on this

**Comment by angeljgomezc** [comment]
closed via #150
