### ISSUE TITLE
Unhandled Runtime Error TypeError: require.e is not a function

### ISSUE THREAD

**Issue by carlomigueldy** [Developer-DAO/DAO-job-board#130]
**Describe the bug**

Seems like the Next.js dynamic imports isn't working as what we expect, it's throwing me an error on dev.

**To Reproduce**

1. Run dev server by `yarn dev`
2. Go to http://localhost:3000/post-job

**Expected behavior**

Should open the page without error on dev

**Screenshots**

![image](https://user-images.githubusercontent.com/45052332/144149596-daa03645-5ca6-4fac-8980-336338bee16d.png)

**Comment by carlomigueldy** [comment]
I think this may be happening to me only

**Comment by carlomigueldy** [comment]
I deleted node_modules and reinstalled dependencies and now it works! 👀 

Closing this issue now

**Comment by kyndaqtepammy** [comment]
I'm actually facing the same issue

**Comment by AbdUlHamedMaree** [comment]
Me too, sometimes it works, and sometimes it breaks on dev.
But the customer reported that this page is throwing an `Application error` sometimes on production

**Comment by mlarcher** [comment]
I have the issue too, but only once in a while. It's hard to figure out the conditions to trigger it, but there'e definitely something fishy in there that should be investigated. I suggest to reopen the issue so that it is kept in sight for the team.

**Comment by ronaldsutantio-acn** [comment]
I am facing the same issue. 
using this version: "next": "12.1.6",
but the error gone when i use async and await method like the following:
`const DynamicHeader = dynamic(async () => await import('../components/header'))`
but sometimes it works and sometimes the component not being rendered, works if i refresh the page.

please investigate this issue.

**Comment by ronaldsutantio-acn** [comment]
deleting node_modules then reinstall the dependencies doesn't help on my end

**Comment by ydax** [comment]
Having this issue too

**Comment by devsirius44** [comment]
1. Check that you do not have files in models directory that are not exporting anything.
2. Check that your exports are functions with same parameters as the instance it is being called in the require statement.
In any case like mine, I had empty files in my models directory. require(...) is not a function simply because the index logic is iterating over and importing files that do not export anything from the models directory.

**Comment by f0rmat1k** [comment]
you should reopen this issue. I have the same and reinstalling doesn't help

**Comment by f0rmat1k** [comment]
i tried to investigate:
i get this error
![image](https://github.com/Developer-DAO/DAO-job-board/assets/769992/a254167b-307d-405e-9a35-45a540b948fe)

And look at `dynamic` source and saw it:
![image](https://github.com/Developer-DAO/DAO-job-board/assets/769992/e10fceb5-d1ba-4349-bddc-cdf04758d70b)

Looks like it's connected

**Comment by vucuongkg** [comment]
Having same issue, sometimes happen. Please fix it
