### ISSUE TITLE
Small Database Change 

### ISSUE THREAD

**Issue by angeljgomezc** [Developer-DAO/DAO-job-board#14]
@carlomigueldy Hey mate! I've been thinking of changing the wording in database from `category` and instead use `keyword`.

This way it's easier to map users, jobs, and gigs.

What do you think?

**Comment by carlomigueldy** [comment]
It's throwing a 404 error @angeljgomezc , can you create a draft pull request in this repo instead so we can take look when Vercel creates a build for it?

**Comment by carlomigueldy** [comment]
@angeljgomezc  Wouldn't it still be the same if we're only just changing how it's spelled?

**Comment by angeljgomezc** [comment]
> 
> 
> @angeljgomezc Wouldn't it still be the same if we're only just changing how it's spelled?

yes! It's pretty much the same. My point was - which one feels more fitting? Keywords seems more general as people can map *anything* to their jobs/profiles (e.g. Polywork's badges) while categories sort of refers to job-related stuff which may limit what people can map to their profiles/jobs/gigs 

Or do you think categories fits better?

**Comment by carlomigueldy** [comment]
I see that makes sense. Yeah it's important to have a better name to that. Let's go with keywords!

Categories is maybe too generic or broad? Also last night I was able to browse those job portals that was linked into the Discourse discussion about the DAO Job Board. 

Do we also limit the amount of keywords they can add up into their profile, job posting or gig posting?

**Comment by carlomigueldy** [comment]
Also for the current design in the database, it's going to allow us to have auto-completes like the one when we add keywords/categories before we get to publish a blog in [dev.to](http://dev.to/) and yeah lots of filter by keywords, or see all jobs with keyword "XYZ", or we can have a widget count that says there's N jobs for this keyword, and anything we can think of.
