### ISSUE TITLE
Job Cards - Turning New Designs into Code

### ISSUE THREAD

**Issue by angeljgomezc** [Developer-DAO/DAO-job-board#155]
**Is your feature request related to a problem? Please describe.**

Current design on the job list is outdated. We already have new designs to work on at https://www.figma.com/file/qGlR5rEinlbUgWmbogXunz/Design-System-%2F-Jobs-Board?node-id=444%3A2525

**JOB CARD**
![image](https://user-images.githubusercontent.com/53134194/145625193-d97fc57c-5dc8-4cbc-99da-5d7e08999ef3.png)

**Describe the solution you'd like**

This issue is for anyone who wants to participate to develop the new Job Cards. These will be located in the `/components/jobs/JobCard.tsx` component

If you want to build them up, follow the design mockup at: https://www.figma.com/file/qGlR5rEinlbUgWmbogXunz/Design-System-%2F-Jobs-Board?node-id=444%3A2525

**Additional context**

This is ONLY for the JobItem component. We're separating the different components before going forward, so it's easier for everyone to participate.

Remember to follow the design details on the Figma file (don't worry about responsiveness for now)

Want to help with this? 

1. Write a comment below, tell us whether you can tackle the issue and how much time it will take you 
2. We'll assign you the issue so you can start working on it
3. We'll expect you to finish the development in the same timeframe you mentioned earlier (or at least to not take twice as much)
4. If you take more time, we'll ask you for updates. If you can't finish for any reason, or you're taking too long, we'll **unassign** you and assign someone else
5. Feel free to ask for any questions before starting so you can be well-prepared 

Also, we're active on Discord, so hop on the #job-board-project channel whenever you want and ask for help if needed :)

**Comment by krames12** [comment]
I can take this issue if nobody else is already working on it. Should take me a few days (3-4?) since I'm a little limited on non-work dev time.

**Comment by mweiss427** [comment]
I'm going to take a stab at this. I'm a first-timer, I will report tomorrow on an update.  No clue on time.  If you need this ASAP, start working and tell me to stop, I'll find something else.

**Comment by angeljgomezc** [comment]
> I'm going to take a stab at this. I'm a first-timer, I will report tomorrow on an update. No clue on time. If you need this ASAP, start working and tell me to stop, I'll find something else.

Hey! We already have someone working on this!

**Comment by mweiss427** [comment]
Sounds good. I got to reading documents so didn't even start.
