### ISSUE TITLE
Modify Dashboard - Turning New Designs Into Code 

### ISSUE THREAD

**Issue by angeljgomezc** [Developer-DAO/DAO-job-board#157]
Is your feature request related to a problem? Please describe.

Current design on the Dashboard (Sidebar) is outdated. We already have new designs to work on at https://www.figma.com/file/qGlR5rEinlbUgWmbogXunz/Design-System-%2F-Jobs-Board?node-id=173%3A2

**HIRING MODE**
![image](https://user-images.githubusercontent.com/53134194/145624870-bac5ba5c-2405-469e-904b-f83c2ff75bb3.png)

**EARNING MODE**
![image](https://user-images.githubusercontent.com/53134194/145624898-adde3a7b-4355-4385-b058-88fa473ca013.png)

Describe the solution you'd like

This issue is for anyone who wants to participate to develop the new Dashboard. These will be located in the `/components/navigation/Dashboard.tsx` component

If you want to build them up, follow the design mockup at: https://www.figma.com/file/qGlR5rEinlbUgWmbogXunz/Design-System-%2F-Jobs-Board?node-id=173%3A2

Additional context

This is ONLY for the `Dashboard` component. We're separating the different components before going forward, so it's easier for everyone to participate.

Remember to follow the design details on the Figma file (don't worry about responsiveness for now)

Want to help with this?

1. Write a comment below, tell us whether you can tackle the issue and how much time it will take you

2. We'll assign you the issue so you can start working on it

3. We'll expect you to finish the development in the same time frame you mentioned earlier (or at least to not take twice as much)

4. If you take more time, we'll ask you for updates. If you can't finish for any reason, or you're taking too long, we'll unassign you and assign someone else

5. Feel free to ask for any questions before starting so you can be well-prepared

Also, we're active on Discord, so hop on the #job-board-project channel whenever you want and ask for help if needed :)

**Comment by m-t-a97** [comment]
I would like to be assigned this issue if no one else is working on this. Thanks in advance.

**Comment by angeljgomezc** [comment]
> I would like to be assigned this issue if no one else is working on this. Thanks in advance.

Great! How long do you think this will take you?

**Comment by m-t-a97** [comment]
It should take around 3-4 days roughly.

**Comment by angeljgomezc** [comment]
Hey @PBillingsby - I know we still don't have some of the pages listed in the design for `Earning` and `Hiring`, but we still need those.

You told me you weren't working on front-end the next few days - mind if I finish this then?

**Comment by PBillingsby** [comment]
@angeljgomezc It's all yours!

**Comment by angeljgomezc** [comment]
closed by #191 and #200
