### ISSUE TITLE
Modify Navbar/Header - Turning New Designs into Code

### ISSUE THREAD

**Issue by angeljgomezc** [Developer-DAO/DAO-job-board#159]
Current design of the Navbar/Header is not responsive nor good-looking enough to match the designs at: https://www.figma.com/file/qGlR5rEinlbUgWmbogXunz/Design-System-%2F-Jobs-Board?node-id=107%3A3

Check the Figma file and develop a component just like it. 

![image](https://user-images.githubusercontent.com/53134194/145691080-8ba87e3d-5cb3-4869-93f4-d71375d55f59.png)

This issue is for anyone who wants to participate to develop the new Navbar. This will be located in the `/components/navigation/Navbar.tsx` component

If you want to help building this, follow the design mockup at: https://www.figma.com/file/qGlR5rEinlbUgWmbogXunz/Design-System-%2F-Jobs-Board?node-id=470%3A721

Additional context

This is ONLY for the `Navbar` component. We're separating the different components before going forward, so it's easier for everyone to participate.

Remember to follow the design details on the Figma file (don't worry about responsiveness for now)

Want to help with this?

1. Write a comment below, tell us whether you can tackle the issue and how much time it will take you

2. We'll assign you the issue so you can start working on it

3. We'll expect you to finish the development in the same time frame you mentioned earlier (or at least to not take twice as much)

4. If you take more time, we'll ask you for updates. If you can't finish for any reason, or you're taking too long, we'll unassign you and assign someone else

5. Feel free to ask for any questions before starting so you can be well-prepared. Also, we're active on Discord, so hop on the #job-board-project channel whenever you want and ask for help if needed :)

We're using ChakraUI and NextJS + Typescript for the front-end

**Comment by tarunyadav1** [comment]
Hey @angeljgomezc ,
I can take this issue.  Should take me a few days (3-4 days). 

thanks

**Comment by tarunyadav1** [comment]
Hey @angeljgomezc  ,
I need more time on this task, got some important work. Would it be possible to extend to this Saturday?

Thanks

**Comment by angeljgomezc** [comment]
> Hey @angeljgomezc  ,
> I need more time on this task, got some important work. Would it be possible to extend to this Saturday?
> 
> Thanks!

Take your time!

**Comment by angeljgomezc** [comment]
Hey @tarunyadav1, how are you progressing with this? Let us know if you need any help :)

We're looking to have this ASAP as we're trying to build the MVP

**Comment by tarunyadav1** [comment]
Hey @angeljgomezc ,
I have done some parts, but it's not complete yet. I am able to work on this after the new year. If someone want to take it in the mean time, you can unassigned me.  

thanks

**Comment by angeljgomezc** [comment]
closed by #184
