### ISSUE TITLE
Modify Filter - Turning New Designs Into Code

### ISSUE THREAD

**Issue by angeljgomezc** [Developer-DAO/DAO-job-board#160]
The current design on the Job Filter (right side) is outdated. We already have new designs to work on at https://www.figma.com/file/qGlR5rEinlbUgWmbogXunz/Design-System-%252F-Jobs-Board

JOB FILTERS
![image](https://user-images.githubusercontent.com/53134194/145732698-6fc65fa1-0893-4793-92fb-79c802a437a2.png)

This issue is for anyone who wants to participate to develop the new Dashboard. These will be located in the `/components/jobs/JobFilter.tsx` component

If you want to build this, follow the design mockup at: https://www.figma.com/file/qGlR5rEinlbUgWmbogXunz/Design-System-%2F-Jobs-Board?node-id=415%3A2083

This is ONLY for the `Job Filter` component. We're separating the different components before going forward, so it's easier for everyone to participate.

Remember to follow the design details on the Figma file (don't worry about responsiveness for now)

Want to help with this?

1. Write a comment below, tell us whether you can tackle the issue and how much time it will take you.

2. Ask for access to Doppler (through the Discord channel). We'll assign you the issue so you can start working on it.

3. We'll expect you to finish the development in the same time frame you mentioned earlier (or at least to not take twice as much)

4. If you take more time, we'll ask you for updates. If you can't finish for any reason, or you're taking too long, we'll unassign you and assign someone else

Feel free to ask any questions before starting so you can be well-prepared

Also, we're active on Discord, so hop on the #job-board-project channel whenever you want and ask for help if needed :)

**Comment by angeljgomezc** [comment]
Hey @HKerStanley, how are you progressing with this? Let us know if you need any help :)

We'd love to have this ASAP!

**Comment by HKerStanley** [comment]
Sorry @angeljgomezc I was spending time with family during holiday. Should be able to wrap it up in few days. In the meantime please have a look on my draft PR and let me know if I am going a wrong direction. Much appreciated :)

**Comment by angeljgomezc** [comment]
closed by #175
