### ISSUE TITLE
Manage fonts with `fontsource`

### ISSUE THREAD

**Issue by with-heart** [Developer-DAO/DAO-job-board#167]
[fontsource](https://fontsource.org/) provides open source fonts as npm packages. This gives a number of benefits [which can be seen here](https://fontsource.org/docs/introduction) but mostly I like it because it's less cognitive overhead:

1. install font package
2. import in `_app.tsx`
3. font is ready to go!

You can see an example commit with this change here: [Developer-DAO/developerdao.com@`0b7a740` (#73)](https://github.com/Developer-DAO/developerdao.com/pull/73/commits/0b7a74093359c92d7efae79b9e7bc06e83e382f2)

To make this change in this repo, we'd need to do three things:

- [x] install font packages
- [x] add imports in `_app.tsx`
- [x] remove the existing font `link` from `index.tsx`

**Comment by angeljgomezc** [comment]
I'll get this done later today!
