### ISSUE TITLE
Implement and document color design tokens

### ISSUE THREAD

**Issue by with-heart** [Developer-DAO/DAO-job-board#172]
This is an umbrella issue for tracking implementation+documentation work of [the colors in our new design system](https://www.figma.com/file/qGlR5rEinlbUgWmbogXunz/Design-System-%2F-Jobs-Board?node-id=107%3A3).

According to the definition of done in #171, completing this issue requires three things:

- Update the Chakra `theme` with the new token
- Document the new token in Storybook
- Update existing components/designs to use the new tokens

For the purposes of color tokens, I think it makes sense to combine the first two into one effort and then follow up on that work with the update of existing components/designs.

- [x] #173
- [x] Update existing components/designs to use new design system colors

Once we've completed these tasks, we'll have:

- the colors embedded in our Chakra system
- a Storybook page which documents the colors
- the colors in use throughout our existing components/designs

**Comment by with-heart** [comment]
Before I can create an issue for the "update" piece, we'll need to talk about how Chakra automatically calculates the colors to use for different components—like buttons and the background colors for normal, hover, and active states, or alerts and the `info`, `success`, etc. variants.

I'll follow up on that soon!

**Comment by angeljgomezc** [comment]
closed with #188
