### ISSUE TITLE
Add new colors to Chakra theme and document them in Storybook

### ISSUE THREAD

**Issue by with-heart** [Developer-DAO/DAO-job-board#173]
This issue is for adding the new colors to our Chakra `theme` and creating a documentation page for them in Storybook.

You can see the new colors and their hex codes in our [new design system Figma](https://www.figma.com/file/qGlR5rEinlbUgWmbogXunz/Design-System-%2F-Jobs-Board?node-id=107%3A3), but here's a pic of them:

![image](https://user-images.githubusercontent.com/1954752/146432007-fa7cc6bd-1997-4d65-9da9-a049c4ab5325.png)

There are a few steps required to add these colors and document them:

- Add the new colors to our `theme` object (found in `packages/client/styles/theme.tsx`)

Here's an example of what adding a new color to the `theme` would look like:

```tsx
import {extendTheme} from '@chakra-ui/react'

export const theme = extendTheme({
  colors: {
    newColor: {
      100: '#fff',
      200: '#ddd',
      300: '#bbb',
      400: '#999',
      500: '#777',
      600: '#555',
      700: '#333',
      800: '#111',
      900: '#000',
    }
  }
})
```

- Create a new Storybook stories page and story that renders the colors in a grid similar to the Figma design system colors grid

**Comment by angeljgomezc** [comment]
already worked on at #166 only need to finish the Storybook setup

**Comment by angeljgomezc** [comment]
Close with #165
