### ISSUE TITLE
Develop + design Job Page 

### ISSUE THREAD

**Issue by angeljgomezc** [Developer-DAO/DAO-job-board#18]
- [x] **Job**

Every job page should hold basic info about the job (title, description, job type, position, keywords, company's link with logo, location, compensation, etc.). Plus, it should have a final button people can click to apply (either via email/ or company's website).

**NOTE**: Every job post page should be on the link = `devdaojobboard.com/jobs/companyname/job-title-with-dashes`

**Comment by miralsuthar** [comment]
hey, @angeljgomezc I can try to make both designs in Figma and if you approve can convert it to code.

**Comment by angeljgomezc** [comment]
> 
> 
> hey, @angeljgomezc I can try to make both designs in Figma and if you approve can convert it to code.

Awesome! Yes, that would be great! 

Btw, try to follow the design of similar pages like [CryptoCurrencyJobs](https://cryptocurrencyjobs.co/startups/civic/) for company profiles and [Gitcoin Bounties](https://gitcoin.co/issue/harvest-finance/harvest/27/100027042) for Gigs. 

That's what I had in mind. Of course, it would be great if you also follow a unique approach.

Lastly, I'm migrating everything to Chakra UI today! So, write your UI elements using Chakra - please! 

Apart from that, just thank you for taking part in this :)

**Comment by angeljgomezc** [comment]
What each Gig page should contain: 

- Name (e.g. Need help with NFT collection...)
- Description
- Category (a set of tags like [this](https://imgur.com/a/Gfx86pf))
- Reward and amount (e.g. 1 ETH or 0.05 BTC)
- Timeframe (0-30 days up to +12 Months)

What each Job page should contain:

- Post Title (e.g. Blockchain Engineer)
- Description
- Job Type (e.g. Part Time, Full Time, etc.)
- Job Position (e.g. Engineering, Marketing, etc.)
- Job Compensation (e.g. 10,000-15,000 USD or 2-3 ETH)
- Job Equity (e.g. 0.01% to 1% up to +5%)
- Job Location (e.g. California, US)

**Comment by miralsuthar** [comment]
Hey, @angeljgomezc just finished with the design this is the Figma [link](https://www.figma.com/file/paI9rYA1rje3cDxKpomxWC/DAO-job-board?node-id=0%3A1) of the design and for the quick look this is the image, the left one is for the gig and the right one is for job

![image](https://user-images.githubusercontent.com/57826091/141469764-79ff08ee-d14b-4f35-8a96-301945f865c3.png)
Let me if you need changes. 😃

**Comment by angeljgomezc** [comment]
> Hey, @angeljgomezc just finished with the design this is the Figma [link](https://www.figma.com/file/paI9rYA1rje3cDxKpomxWC/DAO-job-board?node-id=0%3A1) of the design and for the quick look this is the image, the left one is for the gig and the right one is for job
> 
> ![image](https://user-images.githubusercontent.com/57826091/141469764-79ff08ee-d14b-4f35-8a96-301945f865c3.png)
> Let me if you need changes. 😃 

This looks good mate! Thanks!

Will hit you back in a few hours with feedback but seems perfect so far

**Comment by angeljgomezc** [comment]
> 
> 
> Hey, @angeljgomezc just finished with the design this is the Figma [link](https://www.figma.com/file/paI9rYA1rje3cDxKpomxWC/DAO-job-board?node-id=0%3A1) of the design and for the quick look this is the image, the left one is for the gig and the right one is for job
> 
> ![image](https://user-images.githubusercontent.com/57826091/141469764-79ff08ee-d14b-4f35-8a96-301945f865c3.png) Let me if you need changes. 😃

So I went over the design and have some feedback about the Gig page:

1. The "Experience" tab in the gig page is probably not the best idea. While it's helpful, it may also discourage people from applying to gigs because they don't feel like "Expert" yet. Also, most people creating gigs will prefer adding `Expert` in the forms so most gigs will be expert-only (which will probably leave a lot of people out). What do you think about this?

2.  It would also be great if we could change `Open for` to `Timeframe`. There's no reason to open gigs for a certain amount of time, or is it? We should instead allow Gig creators to close them once the find someone for the job. Anyway, this is simply about changing the wording, so it doesn't change much. Timeframe was supposed to be the amount of time a dev had to get the gig done.

3. We should probably add the name of the gig creator to the page. This allows devs to find out more about the person or company who's starting the gig. 

Apart from that, I like the design. It's simple and straightforward. It may look better with some color (check the rest of the site for an idea), but it's really good already and probably much better than I would have designed it.

Also, if you got some neat advice from with-heart, feel free to put that into practice too.

New Chakra UI is being merged today so you're free to start coding once that's up :)

**Comment by miralsuthar** [comment]
yeah, I completely agree with the points that you have pointed out like sometimes I never feel like an "Expert" whenever that tab appears 😄. 

But about adding the colors to the site according to me wouldn't look nice because I have taken the main developer dao website as a reference for the color and adding the color would feel like the colors are added forcefully still I try adding the colors and will send you some design update and if you have any color pattern in mind let me know about that.

**Comment by angeljgomezc** [comment]
> 
> 
> yeah, I completely agree with the points that you have pointed out like sometimes I never feel like an "Expert" whenever that tab appears 😄.
> 
> But about adding the colors to the site according to me wouldn't look nice because I have taken the main developer dao website as a reference for the color and adding the color would feel like the colors are added forcefully still I try adding the colors and will send you some design update and if you have any color pattern in mind let me know about that.

Hey @miralsuthar! We've decided to start with the MVP only having jobs so far. If you could work on the Job page only and leave the Gig for later, that would be ideal!

**Comment by angeljgomezc** [comment]
Hey @miralsuthar! Any progress on the job page? No pressure! Just asking what you've come up with so far!

Remember @with-heart wrote a bit of code on [his branch](https://github.com/Developer-DAO/DAO-job-board/blob/job-details-skeleton/client/pages/job-details.tsx). You can use this as a starting point if you haven't started yet.

Let me know how you're tackling this and if you need any help!

**Comment by miralsuthar** [comment]
hey @angeljgomezc so just for now the data is going to be static right?

**Comment by angeljgomezc** [comment]
> hey @angeljgomezc so just for now the data is going to be static right?

Yes! It's a prototype so far, but we still need the code

**Comment by with-heart** [comment]
> Remember @with-heart wrote a bit of code on his branch. You can use this as a starting point if you haven't started yet.

Yeah, feel free to checkout from my PR and work off that if you'd like!

**Comment by miralsuthar** [comment]
Hey, @angeljgomezc just open the PR for this issue and let me know if you need any changes.
