### ISSUE TITLE
Migrate Components to Chakra UI

### ISSUE THREAD

**Issue by angeljgomezc** [Developer-DAO/DAO-job-board#20]
Chakra saves time and effort as it comes with tons of functionality + a11y that I may otherwise come up with myself

Will try to migrate everything within 2 days

**Comment by with-heart** [comment]
Happy to help with this! Interested in pairing in public on the D_D Discord?

**Comment by angeljgomezc** [comment]
> 
> 
> Happy to help with this! Interested in pairing in public on the D_D Discord?

That sounds like a great idea! When are you available?

**Comment by with-heart** [comment]
I created a lettucemeet so we can figure out a time: https://lettucemeet.com/l/7xqaj

If anyone else wants to join us, feel free to add times! cc @Dhaiwat10 @carlomigueldy

**Comment by Dhaiwat10** [comment]
Added my availability @with-heart 

cc @nazeeh21 @angeljgomezc

**Comment by Nazeeh21** [comment]
Added my availability too!

Cc @miralsuthar

**Comment by carlomigueldy** [comment]
Done added mine!

**Comment by angeljgomezc** [comment]
Looks like Wednesday, Thursday, and Friday from 12 PM to 1 PM works for most of us. If so, I can update Carlo later on (unless someone wants to make the call at a different time?)

**Comment by Dhaiwat10** [comment]
> 12 PM to 1 PM

in which timezone?

**Comment by with-heart** [comment]
I scheduled it Friday in the chunk that almost all of us have in common. You can see it on lettucemeet!

**Comment by carlomigueldy** [comment]
> I scheduled it Friday in the chunk that almost all of us have in common. You can see it on lettucemeet!

Perfect! I was also thinking to suggest we'd do it on Friday. Thanks @with-heart

**Comment by with-heart** [comment]
@carlomigueldy I wish you could be there :( Another time!

**Comment by carlomigueldy** [comment]
Just fits nicely! @with-heart I can stay up for that moment.

![image](https://user-images.githubusercontent.com/45052332/141036949-229c82a0-6570-4324-a67b-3cfbe7772e15.png)

**Comment by angeljgomezc** [comment]
> 
> 
> Just fits nicely! @with-heart I can stay up for that moment.
> 
> ![image](https://user-images.githubusercontent.com/45052332/141036949-229c82a0-6570-4324-a67b-3cfbe7772e15.png)

Awesome to know you can be there mate! Let's do it on Friday then :)

**Comment by carlomigueldy** [comment]
> Awesome to know you can be there mate! Let's do it on Friday then :)

Heck yes! @angeljgomezc 

See you all on Friday! 🎉
