### ISSUE TITLE
Refactor Profile Component 

### ISSUE THREAD

**Issue by angeljgomezc** [Developer-DAO/DAO-job-board#207]
The current design for the Profile Component is outdated. We already have new designs to work on

OLD PROFILE
![image](https://user-images.githubusercontent.com/53134194/149860319-793b01dd-9741-4d09-bf3c-b2f36e965df4.png)

NEW PROFILE
**![image](https://user-images.githubusercontent.com/53134194/150058735-b926955c-3344-478e-8e7f-769a601227df.png)**

This issue is for anyone who wants to participate to develop the new Profile for Users. These will be located in the `pages/developers/[devaddress]` component

If you want to build this, follow the design mockup atbove

This is ONLY for the Profile component. We're separating the different components before going forward, so it's easier for everyone to participate.

So, want to help with this?

1. Write a comment below, tell us whether you can tackle the issue and how much time it will take you.

2 . Ask for access to Doppler (through the Discord channel). We'll assign you the issue so you can start working on it.

3. We'll expect you to finish the development in the same time frame you mentioned earlier (or at least to not take twice as much)

4. If you take more time, we'll ask you for updates. If you can't finish for any reason, or you're taking too long, we'll unassign you and assign someone else

Feel free to ask any questions before starting so you can be well-prepared

Also, we're active on Discord, so hop on the #job-board-project channel whenever you want and ask for help if needed :)

**Comment by Dhaiwat10** [comment]
I'll get this done
