### ISSUE TITLE
Implement Docker for local development

### ISSUE THREAD

**Issue by PBillingsby** [Developer-DAO/DAO-job-board#215]
### Overview 
Recent discussions have been brought (@JoviDeCroock) up about allowing non-members of the DAO to contribute to the job board. With the current use of Doppler for secrets, this will be problematic if we have an influx of keen contributors. The suggestion of implementing Docker for local development was brought up by @carlomigueldy.

### Problem
Allowing members and non-members to contribute means giving access to Doppler and supabase db, which may end up causing problems.

### Proposed solution
Implement Docker into job board repo for local development for all contributors.

**Comment by carlomigueldy** [comment]
How's it going with the setup comrade @daviddale

**Comment by daviddale** [comment]
Sorry old account was still logged into my phone. Will be working on it this weekend.

**Comment by carlomigueldy** [comment]
Oh I see, alright sounds good mate looking forward!

Here's a link for your reference, tysm!

https://supabase.com/docs/guides/local-development
