### ISSUE TITLE
Proposal: using prisma for database query.

### ISSUE THREAD

**Issue by G3root** [Developer-DAO/DAO-job-board#25]
Some of the advantages using prisma with supabase other than `@supabase/supabase-js
`

- **type safety** - prisma generates types for every model based on the schema.
- **schema migrations** - ability to version control  schema migrations
- **awesome DX** - provides auto completion out of the box.
- supports connection pooling for pgbouncer.
- easy database setup for local development .
- has an API for [seeding](https://www.prisma.io/docs/guides/database/seed-database) database locally .

We can start from here https://dev.to/prisma/set-up-a-free-postgresql-database-on-supabase-to-use-with-prisma-3pk6

**Comment by angeljgomezc** [comment]
Hey @G3root! Thanks for the recommendation. 

@carlomigueldy is handling the back-end right now. We're still finishing the front-end before we start with database queries.

What do you think of this idea @carlomigueldy?

**Comment by carlomigueldy** [comment]
Wow. This is great suggestion. 

> has an API for seeding database locally .

I've actually been thinking of how I do this same how it works for Laravel's `php artisan db:seed`. I think adding Prisma will be very convenient. 

Thank you so much for the suggestion let's add this @G3root !

**Comment by G3root** [comment]
> Wow. This is great suggestion. @G3root @angeljgomezc 
> 
> > has an API for seeding database locally .
> 
> I've actually been thinking of how I do this same how it works for Laravel's `php artisan db:seed`. I think adding Prisma will be very convenient. 
> 
> Thank you so much for the suggestion let's add this @G3root !

That's great , I'll send a draft PR today so we can figure out anything odd. 🎉

**Comment by carlomigueldy** [comment]
Let's gooooo @G3root :)
