### ISSUE TITLE
Create a Doppler workspace

### ISSUE THREAD

**Issue by carlomigueldy** [Developer-DAO/DAO-job-board#27]
As per suggestion/recommendation from @JoviDeCrook this will be a great tool for distributing environmental variables :)

I am going to set it up soon and allow it to easily distribute to other devs that'll join into the project

[Doppler](doppler.com)

**Comment by carlomigueldy** [comment]
<img width="1395" alt="Screen Shot 2021-11-15 at 5 16 53 AM" src="https://user-images.githubusercontent.com/45052332/141698964-fb234642-36da-4a7f-bcbc-794629bb3887.png">

Submitted a request to add Doppler integration into this project :)

Hi guys can I get it approved @with-heart @Dhaiwat10

**Comment by with-heart** [comment]
Approved for this project only! Is there anything special we need to do to configure this or make it work with Vercel?

**Comment by carlomigueldy** [comment]
Thank you @with-heart ! 

I am not sure about it yet how it would work with Vercel, but I am going to explore things out! 

Though @JoviDeCroock is more experienced for Doppler

**Comment by JoviDeCroock** [comment]
There is a Vercel integration that can be leveraged which is found on the [vercel marketplace](https://vercel.com/integrations/doppler)

**Comment by carlomigueldy** [comment]
@with-heart I think someone who have access to Vercel can set it up https://www.doppler.com/integrations/vercel

**Comment by carlomigueldy** [comment]
I need to invite some people into the Doppler workspace, can I invite you guys?

@with-heart @Dhaiwat10 @angeljgomezc @JoviDeCroock 

Also if anyone else might be interested just let me know and I will send you an invite, drop your email here

**Comment by JoviDeCroock** [comment]
Feel free to invite me on decroockjovi@gmail.com

**Comment by carlomigueldy** [comment]
Invite sent! @JoviDeCroock 

Caveats on free tier, I am only limited to assigning "Owner" role to anyone who I can send invites to

**Comment by with-heart** [comment]
Hey @carlomigueldy, since we're connecting this to the D_D orgs, I'd prefer to sign up for a Doppler account with the D_D email. Would that be fine?

**Comment by carlomigueldy** [comment]
Hey @with-heart yes please

Can we also get a D_D email account to setup for Supabase projects?

**Comment by carlomigueldy** [comment]
I don't really want to hold control for everything but temporarily I want to hold for now until we got a D_D account for it

**Comment by with-heart** [comment]
I have orgs for both Doppler and Supabase set up! Hook me up with emails and I'll invite

**Comment by carlomigueldy** [comment]
Awesome!! 

Here's my email :) carlomigueldy@gmail.com

**Comment by angeljgomezc** [comment]
> I have orgs for both Doppler and Supabase set up! Hook me up with emails and I'll invite

angel_33gomez@hotmail.com

**Comment by G3root** [comment]
> I need to invite some people into the Doppler workspace, can I invite you guys?
> 
> @with-heart @Dhaiwat10 @angeljgomezc @JoviDeCroock
> 
> Also if anyone else might be interested just let me know and I will send you an invite, drop your email here

nafeesnazik21@gmail.com

**Comment by Dhaiwat10** [comment]
Awesome work @carlomigueldy! My email: dhaiwatpandya@gmail.com

**Comment by carlomigueldy** [comment]
Yo! Invites sent to all @JoviDeCroock @angeljgomezc @G3root @Dhaiwat10

**Comment by carlomigueldy** [comment]
Doppler workspace has been created and a bunch of invites to members were sent, installation steps for Doppler is also added in README. 

A descriptive step-by-step process will be created soon.
