### ISSUE TITLE
Proposal: Integrate I18n

### ISSUE THREAD

**Issue by kasthor** [Developer-DAO/DAO-job-board#37]
Well as the job board might grow but it's still small, i believe it's probably the best time to integrate Internationalization to the project

Also from my experience I believe that getting I18n early in the project also helps to keep the code clean as the Interface level strings are always represented as a 'label'

Later on I can help to provide a translation to spanish :)

**Comment by carlomigueldy** [comment]
Hi yes please let's set it up @kasthor ! 💯
