### ISSUE TITLE
Web3 auth w/ supabase instead of email/pass

### ISSUE THREAD

**Issue by Dhaiwat10** [Developer-DAO/DAO-job-board#4]

**Comment by angeljgomezc** [comment]
maybe useful: https://www.toptal.com/ethereum/one-click-login-flows-a-metamask-tutorial

**Comment by kasthor** [comment]
Made some update to get the button going

Also the package used has a Context which has been applied from _app.tsx for which the account number can be referenced from any place within the app by using the code

```js
import { useEthers } from "@usedapp/core";
.
.
.
  const { account } = useEthers();
```

added a function called formatAccount (locally in the auth file) that i think should be moved to some utils file, but not sure where will it fit, 

also the button is created as a component, but didn't want to mess up any structure so I didn't moved to 'components/'

**Comment by Dhaiwat10** [comment]
I've been looking into this. Hoping to get something going soon

https://github.com/ethereum/EIPs/blob/9a9c5d0abdaf5ce5c5dd6dc88c6d8db1b130e95b/EIPS/eip-4361.md

**Comment by Dhaiwat10** [comment]
@JoviDeCroock shared this snippet which might help us:

```js
export default async function handler(req: NextApiRequest, res: NextApiResponse ) {
  const { walletAddress } = req.body

  // This will be used within a session to verify whether the eth-signature is valid for this nonce.
  const nonce = uuid4();
  const user = await supabase.from('users').select().match({ wallet_address: walletAddress }).single()
  if (user.data) {
    const result = await supabase.from('users').update({ nonce }).eq('wallet_address', walletAddress)
    if (result.data) {
      res.status(200).json(result.data);
    } else {
      res.status(result.status).json(result.error);
    }
    return;
  } else {
    const result = await supabase.from('users').insert({
      wallet_address: walletAddress,
      nonce,
    });

    if (result.data) {
      res.status(200).json(result.data);
    } else {
      res.status(result.status).json(result.error);
    }
  }
}
```

**Comment by JoviDeCroock** [comment]
I think a good flow would be to login like this, this will have the premise that we disconnect the supabase-auth-user (as it relies on email-pw). When we see that the user does not have a profile yet we redirect them to `create-profile` to onboard them.
