### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by carlomigueldy** [Developer-DAO/DAO-job-board#42]
I want to learn more about it and how to use `docker-compose` on this project :) 

It's relatively trivial ticket but if someone does it for fun then we'd be happy to dockerize this repo and we can learn from it how it was setup

**Comment by JoviDeCroock** [comment]
What do you want to dockerize, personally not the biggest fan 😅 I've got quite a bit of experience but have grown more fond of lambda's and use docker for local databases

**Comment by carlomigueldy** [comment]
I was thinking of getting Next.js dockerized? XD But would it be useful? @JoviDeCroock I'd like to know what your thoughts about it

I'm not going for a self-hosted Supabase tho.

**Comment by JoviDeCroock** [comment]
My main thinking behind not putting Next behind docker is that the current development ease is amazing. A new contributor rolls in and just runs yarn and yarn dev and they're off to the races. On top off that, Docker isn't available for non-pro Windows users so I'm always hesitant on it for open-source projects. We could say that we allow for both flows but that kind off scares me in terms of potential divergence.

This is just an opinion though 😅

**Comment by carlomigueldy** [comment]
Ohh I see. But yeah the current state of how the project is right now is fine the way it is.

Thanks for your thoughts on it though :) I'm going to close this issue now
