### ISSUE TITLE
Job Board Main Ideas

### ISSUE THREAD

**Issue by angeljgomezc** [Developer-DAO/DAO-job-board#46]
After having a conversation in Discord about WHERE to take the job board and ship quickly so we can start iterating more concretely - we ended up with a few main points to tackle:

- [x] We need [User Stories](https://github.com/Developer-DAO/DAO-job-board/issues/45) to brainstorm ideas for the job board like below
- [ ] USERS will be allowed to become either _Recruiters_ or _Seekers_ so they can either post Jobs or apply to jobs. 
- [x] The job board will start only with Jobs and get the site shipped with as little complexity as possible
- [x] The Gigs section development will be left for later too (we need to figure out how to allow users to deposit/receive rewards). 
- [x] Company profiles will be left for later (we need to figure out a way to allow companies to sign up / verify it's actually a company) so we'll start only with _Recruiters_
- [x] We need to figure out the perfect User Flow for signing up and creating a profile. We're trying to set up a call with the design guild to get help with UI/UX of the job board (to iterate the MVP quickly) Link to the: [LettuceMeet](https://lettucemeet.com/l/V6PPa)

Check our [User Stories](https://carlomigueldy.notion.site/Job-Board-10257a02e02643ada8e11ad99c8248a6) for a to-do list of these ideas

**Comment by carlomigueldy** [comment]
This is the new link for the Notion board

https://carlomigueldy.notion.site/Job-Board-10257a02e02643ada8e11ad99c8248a6

I updated the User Stories page to be a sub-page, so if we might need to add another page for a different scope/topic, everyone can still access to it

**Comment by angeljgomezc** [comment]
Closed because the main RFC and user stories with all the information about the MVP were created:

https://forum.developerdao.com/t/rfc-user-stories-for-dao-job-board/507
