### ISSUE TITLE
Broken / incorrect 🔗 in the README

### ISSUE THREAD

**Issue by frankTurtle** [Developer-DAO/DAO-job-board#47]
At the bottom of the README, there are two links ( See screenshot below )
1. ISSUES
2. CONTRIBUTING GUIDELINES 

![image](https://user-images.githubusercontent.com/5667044/142257952-af782169-8935-40e9-9f25-1fb9205c16c8.png)

### Link 1 - ISSUES
* The link points here 👉 https://github.com/angeljgomezc/DAO-job-board/issues 
* It should point here 👉 https://github.com/Developer-DAO/DAO-job-board/issues/

### Link 2 - CONTRIBUTING GUIDELINES
* The link returns a `404`
* It should point here - *Maybe* 🤷‍♂️? 👉 https://github.com/Developer-DAO/DAO-job-board#how-to-contribute
* It should not `404` at least

**Comment by angeljgomezc** [comment]
Fixed @frankTurtle! Thank you for this!
