### ISSUE TITLE
Application List 

### ISSUE THREAD

**Issue by angeljgomezc** [Developer-DAO/DAO-job-board#59]
As of now, we have a [mockup for each Job Page 
](https://www.figma.com/file/paI9rYA1rje3cDxKpomxWC/DAO-job-board?node-id=0%3A1) (right component)
![image](https://user-images.githubusercontent.com/53134194/142514400-fa4998af-8d36-4542-b35e-45afadec916c.png)

This is what every developer/job seeker will see as they open a job posting. However, what does every recruiter's job page look like?

We should add an `applicationList` component that shows every developer that's applied so far. It should a tiny application letter + links the developer wants to send. 

This feature would be available for Recruiters who decide to receive applications directly on the site (the default will be their email/website posting).

What do you guys think? @carlomigueldy @JoviDeCroock @frankTurtle @Miral @Dhaiwat10 @kasthor @swetshaw

If we're doing this, feel free to propose a mockup for how every recruiter will see these applications :)

**Comment by frankTurtle** [comment]
I'll take it 💪

**Comment by carlomigueldy** [comment]
That looks good!

**Comment by frankTurtle** [comment]
## I'm confused, I need a bit more clarification 👇

> This is what every developer/job seeker will see as they open a job posting
* You're saying this mockup is what the job seeker sees ✅

> However, what does every recruiter's job page look like?
* Is there no figma UI?

> We should add an `applicationList` component that shows every developer that's applied so far.
* Am I adding it to this mockup? 
* That doesn't seem right 🤔

> If we're doing this, feel free to propose a mockup for how every recruiter will see these applications :)
* I think this answers all my questions ... So this mockup UI doesn't exist yet. 
* The statement is `if we're doing this ... ` when do we decide if we are?

## Thoughts
* I missed the `design` tag, I have no design software, but I can try something
* This does not seem like a task for me - until we're at the implementation phase 
* 🙏My apologies, I only looked at the title and screenshot before jumping in - I was caught up in the Sotheby's auction tonight.

**Comment by swetshaw** [comment]
Hey @angeljgomezc , I think first we should decide if our job board wants to handle companies viewing the applicants on our website. 

The other approach can be:

- The DAO provides the link to the job page/website where they have opened this job role.

- Developers who want to apply for a DAO can visit this link and apply for the job.

How are we planning to do it? If we are planning to handle this on our website itself then I have one more suggestion.

- The developers should also be able to see the list of jobs that they have applied to.

- The developers should also be able to see if the DAO that they have applied to is interested in their application and wants to take things forward.

**Comment by angeljgomezc** [comment]
> ## I'm confused, I need a bit more clarification 👇
> 
> > This is what every developer/job seeker will see as they open a job posting
> * You're saying this mockup is what the job seeker sees ✅
> 
> > However, what does every recruiter's job page look like?
> * Is there no figma UI?
> 
> > We should add an `applicationList` component that shows every developer that's applied so far.
> * Am I adding it to this mockup? 
> * That doesn't seem right 🤔
> 
> > If we're doing this, feel free to propose a mockup for how every recruiter will see these applications :)
> * I think this answers all my questions ... So this mockup UI doesn't exist yet. 
> * The statement is `if we're doing this ... ` when do we decide if we are?
> 
> ## Thoughts
> * I missed the `design` tag, I have no design software, but I can try something
> * This does not seem like a task for me - until we're at the implementation phase 
> * 🙏My apologies, I only looked at the title and screenshot before jumping in - I was caught up in the Sotheby's auction tonight. 
> 

Hey @frankTurtle! Totally fine! I should also name/explain issues better on these issues from now on.

**Comment by angeljgomezc** [comment]
> Hey @angeljgomezc , I think first we should decide if our job board wants to handle companies viewing the applicants on our website.
> 
> The other approach can be:
> 
> * The DAO provides the link to the job page/website where they have opened this job role.
> * Developers who want to apply for a DAO can visit this link and apply for the job.
> 
> How are we planning to do it? If we are planning to handle this on our website itself then I have one more suggestion.
> 
> * The developers should also be able to see the list of jobs that they have applied to.
> * The developers should also be able to see if the DAO that they have applied to is interested in their application and wants to take things forward.
> 
> I request @angeljgomezc @Dhaiwat10 @with-heart @carlomigueldy to give their feedback so that we start working on this issue.

YES! 

I added both options because there's probably an advantage in allowing recruiters to see job applications directly on the site. This way they can separate people from DevDAO and other devs on the site from those applying directly through their website/email 

What I had in mind was either of these:

1. A Recruiter posts a job. They can decide whether they want to add their own email/job-post-url on job creation. If they don't, the application list is automatically deployed, so they'll see applicants DIRECTLY through our job board.

2. A Recruiter posts a job. They need to add their email/job-post-url on creation. If they want, they can activate the option to ALSO receive applications through the site (this will help them sort through people and see their profiles as we're allowing everyone to create). We can charge a bit for this extra feature or at least promote any other feature we may also offer later (like our own sorting help - but this is a loose idea)

3.  We offer both options as OPTIONAL features. They can decide whether they use both at the same time or only one (through their methods or through the site) 

As for the "Jobs I've Applied To" that's a feature we will probably need in that case. But we should probably discuss this a bit further before we go into that (even though it'll be really helpful)

**Comment by swetshaw** [comment]
Okay @angeljgomezc , assign me this issue and parallelly we can discuss this over a discord call and take things forward. What do you say?

**Comment by carlomigueldy** [comment]
> Hey @angeljgomezc , I think first we should decide if our job board wants to handle companies viewing the applicants on our website.
> 
> The other approach can be:
> 
> * The DAO provides the link to the job page/website where they have opened this job role.
> * Developers who want to apply for a DAO can visit this link and apply for the job.
> 
> How are we planning to do it? If we are planning to handle this on our website itself then I have one more suggestion.
> 
> * The developers should also be able to see the list of jobs that they have applied to.
> * The developers should also be able to see if the DAO that they have applied to is interested in their application and wants to take things forward.
> 
> I request @angeljgomezc @Dhaiwat10 @with-heart @carlomigueldy to give their feedback so that we start working on this issue.

I like both by the way

**Comment by swetshaw** [comment]
Hi @angeljgomezc , I have tried to design a minimalist page for the application list, you can access the Figma file [here](https://www.figma.com/file/g3I1A9yV6YPwPnycMFcgCu/Application-list-DD?node-id=45%3A356)

What do you think about it? Waiting for your review 🙂

**Comment by angeljgomezc** [comment]
> Hi @angeljgomezc , I have tried to design a minimalist page for the application list, you can access the Figma file [here](https://www.figma.com/file/g3I1A9yV6YPwPnycMFcgCu/Application-list-DD?node-id=45%3A356)
> 
> What do you think about it? Waiting for your review 🙂

Looks great! This is like an application dashboard for the site, and it matches with what we were thinking! Thank you!

By the way, we're getting help from the design guild when it comes to the visuals, so you won't have to build mockups for anything going forward (or that's the plan)

Either way, would be great if you shared this in the job-board channel for everyone to see!

**Comment by carlomigueldy** [comment]
> Hey @angeljgomezc , I think first we should decide if our job board wants to handle companies viewing the applicants on our website.
> 
> The other approach can be:
> 
> * The DAO provides the link to the job page/website where they have opened this job role.
> * Developers who want to apply for a DAO can visit this link and apply for the job.
> 
> How are we planning to do it? If we are planning to handle this on our website itself then I have one more suggestion.
> 
> * The developers should also be able to see the list of jobs that they have applied to.
> * The developers should also be able to see if the DAO that they have applied to is interested in their application and wants to take things forward.
> 
> I request @angeljgomezc @Dhaiwat10 @with-heart @carlomigueldy to give their feedback so that we start working on this issue.

We've involved this in the RFC however rephrased but the idea was there! Thank you @swetshaw 

https://forum.developerdao.com/t/rfc-user-stories-for-dao-job-board/507

**Comment by angeljgomezc** [comment]
Moved to #118 as discussion
