### ISSUE TITLE
Create hooks relevant to fetching data from DB

### ISSUE THREAD

**Issue by carlomigueldy** [Developer-DAO/DAO-job-board#6]

**Comment by dizthewize** [comment]
@carlomigueldy If you need any assistance with this feel free to reach out to me

**Comment by carlomigueldy** [comment]
Thank you @dizthewize , we had our conversation from Discord DMs! 

For context to other people chiming into the project, I have create a generic hook then we can use that for making queries, etc. The hook's name is `useSupabase` where it takes a generic type argument, typically it's a data model that we'll pass into it.

It's in this PR https://github.com/Developer-DAO/DAO-job-board/pull/22 so you can take a look if you want :)

I'm closing this issue now as the issue was already merged a week ago.
