### ISSUE TITLE
Adding Profile Image/Avatar

### ISSUE THREAD

**Issue by angeljgomezc** [Developer-DAO/DAO-job-board#60]
Every user will have the chance to change their PFP through the [Profile Form ](https://dao-job-board-murex.vercel.app/create-profile)

We have the mockup for the profile form, but we should still add the input so users can add the image they prefer and upload it. We need a mockup for this input (feel free to propose something via Figma + push a PR to the repo afterward)

Here's the [create-profile file](https://github.com/Developer-DAO/DAO-job-board/blob/main/client/pages/create-profile/index.tsx). The add-avatar component should rest on the [create-profile folde](https://github.com/Developer-DAO/DAO-job-board/tree/main/client/components/create-profile)r in `components`

I think we could use [Fleek's file storage ](https://fleek.co/storage/) to store these pictures then add them to the database only as URLs (this will make them slower to fetch, given IPFS slowness), but makes the website more web3 friendly in the process. 

What do you guys think? @carlomigueldy @with-heart @JoviDeCroock @swetshaw @Dhaiwat10 @miralsuthar @frankTurtle

**Comment by diegoalzate** [comment]
Hey, i think i can give this a shot :)

**Comment by carlomigueldy** [comment]
> I think we could use Fleek's file storage to store these pictures then add them to the database only as URLs (this will make them slower to fetch, given IPFS slowness), but makes the website more web3 friendly in the process.

Hey for the storage, I got one in mind and it's pretty simple to use it. It's IPFS + FileCoin together for persistence. 

Web3 Storage -> https://web3.storage/

**Comment by Dhaiwat10** [comment]
We def need this. Good luck @diegoalzate and feel free to ask for help

**Comment by diegoalzate** [comment]
I think i finished the basic functionalities, but i have some doubts.

- First of all i created a web3Storage account with my github account and generated an api key with that account, I'm not sure if we should create this api key with another account
- Another doubt is concerning an update functionality with web3Storage, i can successfully store a file but i havent been able to see how i can update an existing file directory.
- Lastly, not sure how to structure the PR so everything is explained in a clear and consice way, not sure if theres like a convention or guide to do that properly

**Comment by carlomigueldy** [comment]
> Lastly, not sure how to structure the PR so everything is explained in a clear and consice way, not sure if theres like a convention or guide to do that properly

I am gonna take a look at some templates for the pull requests in its most simplest form so everyone that creates a pull request will have a guide on what information to put

**Comment by diegoalzate** [comment]
@carlomigueldy @Dhaiwat10 @angeljgomezc
Hi! I'm still a bit stuck on this, not sure if the database connection changes the way this feature should work.

**Comment by angeljgomezc** [comment]
Hey @diegoalzate, where are you stuck exactly? The database isn't finished yet, so you probably shouldn't worry about that. As long as you can set up upload to IPFS and you get the link of the file being uploaded, that should be enough.

Also, a simple UI would suffice for this job (takes the[ new profile form](https://dao-job-board.vercel.app/create-profile) as a guide).

**Comment by carlomigueldy** [comment]
> @carlomigueldy @Dhaiwat10 @angeljgomezc Hi! I'm still a bit stuck on this, not sure if the database connection changes the way this feature should work.

Yo, if you're directly integrating this and adding actual record to database, the attribute `avatar_url` is up-to-date. However if not the case then you can add TODOs that the returned value for the IPFS upload needs to be saved into the database.

**Comment by angeljgomezc** [comment]
closed via #139

**Comment by angeljgomezc** [comment]
closed via #139
