### ISSUE TITLE
Proposal: Roadmap Page

### ISSUE THREAD

**Issue by carlomigueldy** [Developer-DAO/DAO-job-board#67]
### Overview

A page where the users can see a timeline of a set of features that were implemented on each month. And they will also see upcoming features with a time estimation that we can ship it by a given timeframe? Or maybe only have a date displayed if the features were implemented. By having a roadmap page in the website, that could bring excitement for our users and may also encourage potential contributors to the project.

What are your thoughts on this everyone? :)

**Comment by angeljgomezc** [comment]
We didn't make this so I'm closing it. Probably reopen later if we get the roadmap going.
