### ISSUE TITLE
Proposal: Add ability to add POAP/Completion NFTs for user profile

### ISSUE THREAD

**Issue by PBillingsby** [Developer-DAO/DAO-job-board#74]
Allow user to display POAPs and NFTs from completed courses/tutorials etc.

Advantages:  User to be able to show efforts and involvement in the open source and web3 communities to prospective employers.

**Comment by carlomigueldy** [comment]
I like this idea by the way so it's a +1 from me

I have a question though, how do we retrieve POAPs, what API do we use? The first thing that comes to mind is using The Graph or ethers.js library

**Comment by PBillingsby** [comment]
@carlomigueldy I reached out to POAP and got the API. I'm going to look further into the API today

https://api.poap.xyz/documentation/static/

**Comment by frankTurtle** [comment]
🤙🤙 I like these, too!

**Comment by carlomigueldy** [comment]
> @carlomigueldy I reached out to POAP and got the API. I'm going to look further into the API today
> 
> https://api.poap.xyz/documentation/static/

Awesome stuff thank you!

**Comment by carlomigueldy** [comment]
This proposal is involved in this RFC! 🚀 

https://forum.developerdao.com/t/rfc-user-stories-for-dao-job-board/507
