### ISSUE TITLE
Update database attributes to match UI forms 

### ISSUE THREAD

**Issue by carlomigueldy** [Developer-DAO/DAO-job-board#79]
### Overview

There were lots of additions since so the database attributes got outdated overtime. We need to update the attributes that is inline to the current UI that we have in the website. My recommended approach to figure out what attributes to add, change or removed is to go over the website, check out the existing implemented forms and try to come up which attributes that are need to be added.

**Comment by shindeajinkya** [comment]
https://shrouded-egg-969.notion.site/Dev-DAO-job-board-missing-DB-attributes-28af617997e8480dbd1e088ec5b1d2cf

have found these missing fields for DB and forms both will update for other forms too in some time

**Comment by angeljgomezc** [comment]
> https://shrouded-egg-969.notion.site/Dev-DAO-job-board-missing-DB-attributes-28af617997e8480dbd1e088ec5b1d2cf
> 
> have found these missing fields for DB and forms both will update for other forms too in some time

Hey mate! We need to re-do the database following the forms and not the other way around - so getting rid of the fields in the database that we aren't using should be the best way to go.

**Comment by carlomigueldy** [comment]
You can also refer to this document if you may come up with them database attributes @shindeajinkya 

RFC Document
https://forum.developerdao.com/t/rfc-user-stories-for-dao-job-board/507

**Comment by PBillingsby** [comment]
@carlomigueldy Can you review the current db info and see if theres anything in the schema that doesn't look right to you? If all the polymorphic relationships are connected then I believe this issue is good to be closed, just wanted a second opinion.

**Comment by angeljgomezc** [comment]
closed via #150
