### ISSUE TITLE
Security: Validating a job posting

### ISSUE THREAD

**Issue by carlomigueldy** [Developer-DAO/DAO-job-board#84]
### Overview

While having a random chat with @PBillingsby we were talking about how people could potentially flood the job board using bots, they can create a new wallet and flood more with not useful information thus that might not give us a good reputation or perspective for our users that our job board is spammy with scammy postings. Tackling this early on or finding a solution would be great.

### Solution

@PBillingsby suggested to have an admin dashboard where we can manage job postings, that we can maybe ban or suspend users however this approach can make the job board a bit more centralized since we're controlling what users would see. But it's for creating a good user experience for our users that we would prevent scammy-spammy postings. 

It would be cool that if we can come up with an algorithm that filters or prevents this kind of problems but it might be difficult. 

However if you might have a better suggestion on how we go about it please comment down below, we'd love to discuss it with you.

**Comment by angeljgomezc** [comment]
Maybe we can start charging people for job postings before it gets crowded?

**Comment by PBillingsby** [comment]
@angeljgomezc @carlomigueldy I think this definitely raises the security more if the job posting is a paid service. I think we should look into this at least

**Comment by PBillingsby** [comment]
@angeljgomezc @carlomigueldy A thought I had was wouldn't a job poster have to pay gas for a post? This might deter a lot of spam bots based on this alone.

**Comment by carlomigueldy** [comment]
> @angeljgomezc @carlomigueldy A thought I had was wouldn't a job poster have to pay gas for a post? This might deter a lot of spam bots based on this alone.

We're most likely not using Ethereum Mainnet since it'll be very expensive to create a job posting, so we're most likely finding L2s solution. I don't have much knowledge about the other chains yet and on what the perfect use case for this.

**Comment by carlomigueldy** [comment]
Btw I created a Discussion here, thought if it'd be great having all of it in there. So I added a link to reference in this issue

For anyone that wants to continue following the thread or want to get involved with discussion, it continues here

https://github.com/Developer-DAO/DAO-job-board/discussions/108
