### ISSUE TITLE
Proposal: Shorten required char length for job title for job post form

### ISSUE THREAD

**Issue by PBillingsby** [Developer-DAO/DAO-job-board#86]
## Overview
While looking over the code I noticed that with the job post form there is a `minLength` of 10 for the job title. 

## Problem
Have not considered jobs like Tech Lead, that have less than 10 characters

## Proposal
Shorten required character count to 7 to account for shorter job titles: `minLength={7}` `<Text fontSize="xs">At least 7 characters</Text>` `Make sure title is at least 7 characters long`

**Comment by angeljgomezc** [comment]
Fixed at #78

**Comment by angeljgomezc** [comment]
Fixed at #78
