### ISSUE TITLE
Add Forms for Jobs, Gigs, and Profile Creation

### ISSUE THREAD

**Issue by angeljgomezc** [Developer-DAO/DAO-job-board#9]

**Comment by carlomigueldy** [comment]
I suggest that you use this https://react-hook-form.com/

**Comment by angeljgomezc** [comment]
> 
> 
> I suggest that you use this https://react-hook-form.com/

Found this too late mate :(

Already built the forms from scratch but thank you (I tried to make them as fitting for the Jobs/Gigs as necessary)

Will check this further and see if it saves me time with the Dev and Company profile forms (already half-way through so let's see)

**Comment by angeljgomezc** [comment]
> 
> 
> _No description provided._

Forms for Post Job and Post Gig already working on production link:

Gig = https://job-board-sage.vercel.app/post-gig

Post = https://job-board-sage.vercel.app/post-job

@carlomigueldy @Dhaiwat10 

Check and let me know what you guys think :)

**Comment by carlomigueldy** [comment]
Btw can you create a pull request in this repo, we can't view it with that link. Seems to be broken @angeljgomezc

**Comment by angeljgomezc** [comment]
> 
> 
> Btw can you create a pull request in this repo, we can't view it with that link. Seems to be broken @angeljgomezc

Links updated! I deleted the previous deployment as it was on the wrong account

**Comment by angeljgomezc** [comment]
Finished the front-end for the forms 

Create-Profile Form = https://dao-job-board-murex.vercel.app/create-profile
Create Job Post Form= https://dao-job-board-murex.vercel.app/post-job
Create Gig Post Form = https://dao-job-board-murex.vercel.app/post-gig

@with-heart @carlomigueldy 

Would love at least a bit of feedback on them. They're pretty rudimentary still

**Comment by swetshaw** [comment]
That's a very neat UI @angeljgomezc .
One feedback for post-job page:
Shouldn't we have a dedicated field to collect salary information from the company? That will be one of the main points of interest for anyone looking for a job? What do you think?

**Comment by angeljgomezc** [comment]
> 
> 
> That's a very neat UI @angeljgomezc . One feedback for post-job page: Shouldn't we have a dedicated field to collect salary information from the company? That will be one of the main points of interest for anyone looking for a job? What do you think?

Hey @swetshaw! Indeed, salary information is essential. The Job-Post form already has a `Compensation` section in the `Job Details` page (if that's what you're referring to). Compensation is pretty much the salary + whatever the company wants to pay as an extra (bonuses, etc.)
